name: 'Jen & Chris Creed'
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.22586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eee1f3'
    - '#7f6a59'
    - '#b0947f'
    - '#312a20'
    - '#36647e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
